# Общие настройки, применяемые ко всем профилям
server:
  port: 8080

logging:
  level:
    root: INFO
    org:
      springframework: INFO

upload:
  dir: classpath:upload
  dir.images: classpath:upload/images

---
# Профиль prod
spring:
  profiles: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/myblog
    driverClassName: org.postgresql.Driver
    username: myblog
    password: 

---
# Профиль dev
spring:
  profiles: dev
  
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: admin
    password: 
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---
# Профиль test
spring:
  profiles: test

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: admin
    password: 
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true
      path: /h2-console
