# Общие настройки, применяемые ко всем профилям
server:
  port: 8080

spring:
  main:
    banner-mode: off

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: admin
    password: 
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true
      path: /h2-console
      
logging:
  level:
    root: ERROR
    org:
      springframework: ERROR

upload:
  dir: classpath:upload
  dir.images: classpath:upload/images

---
# Профиль prod
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/myblog
    driverClassName: org.postgresql.Driver
    username: myblog
    password: 

---
# Профиль dev
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: admin
    password: 
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true
      path: /h2-console

